---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://mvaude.github.io/hugo_boilerplate"
title: "Hugo Blog Template for GitHub Pages"
canonifyurls: true
...

